baseURL: "https://russfrith.com"
languageCode: en-us
title: Russell ‛Russ’ Frith
theme: PaperMod
env: production

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

params:
  label:
    icon: "/images/blog-logo.svg"
    iconHeight: 35

  homeInfoParams:
    Title: "Welcome to My Blog"
    Content: I am a seasoned software developer. I share what I have learned, alongside the mistakes that I have made and continue to make so that you don’t have to. However, if you code, you too will make mistakes and learn along with me.

  socialIcons:
    - name: twitter
      url: "https://twitter.com/russfrith"
    - name: linkedin
      url: "https://www.linkedin.com/in/russellfrith/"
    - name: github
      url: "https://github.com/russfrith"  
    - name: rss
      url: "https://russfrith.com/index.xml"
  
  ShowReadingTime: true
  ShowShareButtons: true
  ShowFullTextinRSS: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
